### ISSUE TITLE
due to Typeerror I can get the graph!

### ISSUE THREAD

**Issue by mjonyh** [stefanSchinkel/gantt#1]
I have used the sample.json 

In my case, it gives the following error:
     TypeError: object of type 'map' has no len()

and shows only skull of the graph:
![foo](https://cloud.githubusercontent.com/assets/6975114/19212815/b3cba7a6-8d7b-11e6-8a1f-b841683d9a8d.png)

**Comment by stefanSchinkel** [comment]
Hi, 

I can't replicate the error. I just tried again in it works just fine for me, indeed I just updated the image in the README using sample.json

Can you call the wrapper (runner.py) and paste the full error log if it fails again. 

Stefan

**Comment by stefanSchinkel** [comment]
Couldn't replicate.

**Comment by SignMyPublicKey** [comment]
Can confirm this error. Seems to me that there is a compatibility issue between Python2 and Python3.

Error found in method render(), in this line: `self.barlist = plt.barh(self.yPos, self.durations...`
By changing the type of self.durations to list (e.g. `list(self.durations)` this issue is solved.

Another error is found in method addMilestones(), in line: `for key in self.milestones.iterkeys():`, easy fix by changing it to `for key in self.milestones.keys():`

Works fine for me after that. Python3.6, Matplotlib 2.2.2

**Comment by stefanSchinkel** [comment]
@SignMyPublicKey since it's working w/ for you already, could you issue a PR for that? 

thx,
Stefan

**Comment by SignMyPublicKey** [comment]
Of course, you should've received one. Thanks for making my project work easier by the way!

**Comment by stefanSchinkel** [comment]
@SignMyPublicKey  glad to hear it's useful for you!

thx a lot,
Stefan

**Comment by mjonyh** [comment]
Thanks a lot @SignMyPublicKey
